web:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/logbook
    tag: ""
  ingress:
    hostname: passage.ijmacd.com
    path: /logbook
    certName: passage-cert
  db:
    name: passage
    user: passage_user
  local:
    enabled: false
mariadb:
  enabled: false
externalDB:
  enabled: true
  # host: 3.10.39.191
  # host: aws.ijmacd.com
  # host: ip-172-31-35-1
  host: ip-172-31-35-1.eu-west-2.compute.internal
